### ISSUE TITLE
New miniatures being created name themselves with underscores, for example, catfolk_rogue_M01 instead of "Catfolk Rogue"

### ISSUE THREAD

**Issue by Roxfall** [LordAshes/TaleSpire-CustomMiniPlugin#3]
![image](https://user-images.githubusercontent.com/30673911/126072406-73a1fba5-7d0d-46b2-9c44-c28eeda8b5f9.png)

**Comment by LordAshes** [comment]
Prior to the latest build of the TS software, TS used "nice" default names
for new minis. As of the last build, new minis default to no name at all.
The Creature Name is actually null. Since Stat Messaging requires a name,
it generates a default name based on available information. Since the
previous "nice" name is not readily available (without binding the code to
a index.json file which is not actually used by TS and thus could be
removed) the mesh name is used instead.

The GM Tools can be used to rename the mini to any desired name.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Roxfall** [comment]
Kudos to you for responding quickly! Bummer about the _'s.

**Comment by LordAshes** [comment]
Yes, we could add code to replace underscores with spaces to make the name
a little better. However, I want to wait to see if the "nice" names return
in a future TS build since the mesh name in a lot of cases isn't all that
nice. Sometimes it has a name and a number and so on.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by LordAshes** [comment]
As I said, the underscore is not really the problem. Those could be
eliminated fairly easily, it is the fact that instead of a nice name like
"Catfolk Rogue" we get something like "Catfolk_Rogue_M01". So even if the
underscores were replaced it still isn't a nice name in most cases. But the
GM Rename still works and with that you can set it to anything you like.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
