### ISSUE TITLE
When you change to a different, non-default board that already existed, the Ctrl-M menu no longer shows up.

### ISSUE THREAD

**Issue by Roxfall** [LordAshes/TaleSpire-CustomMiniPlugin#5]
Nothing happens when you press left Ctrl-M, so instead of the menu you get the sphere measurement widget.

**Comment by Roxfall** [comment]
This is a problem for both 5.0.1. and 5.0.0

**Comment by Roxfall** [comment]
The red box with the exclamation mark in top left corner keeps blinking. Might be related.

**Comment by LordAshes** [comment]
The blinking exclamation means that TS encountered a problem. You can multi
click on it to open the official TS console but using the BepInEx console
is easier.

Look to see if there are any exceptions thrown before the functionality
fails.

You can also use R2ModMan to remap the CMP keys so that they don't conflict
with the TS tool.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Roxfall** [comment]
![image](https://user-images.githubusercontent.com/30673911/126083968-60bdd52f-7460-476e-9d2c-391056bc3551.png)
This keeps spamming when I load another board after loading a small board with two custom minis, one of them set unique. The second board I load contains neither of the minis, but is fairly large. 
 
The spam does not stop.

**Comment by LordAshes** [comment]
I have noted this problem and will look into it.

Lord Ashes

**Comment by Roxfall** [comment]
Appears fixed in 5.1.0

**Comment by LordAshes** [comment]
Yes. There was an issue which causes a board reload to start getting null
exception which probably was the cause of the CTRL+M not working. The
latest StatMessagingPlugin addressed this. So technically it is not the CMP
5.1.0 but the StatMessagingPlugin update that came with it that fixed the
issue.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
